AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 bucket stack for Xlya app

Resources:
  XlyaS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: xlya-bucket-dev
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

Outputs:
  XlyaBucketName:
    Description: Name of the Xlya S3 bucket
    Value: !Ref XlyaS3Bucket