AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Xlya SAM Root Template

Resources:
  IAMStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: IAM/template.yaml

  CognitoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito/template.yaml

  DynamoDBStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: dynamodb/template.yaml

  AuthFeature:
    Type: AWS::Serverless::Application
    Properties:
      Location: auth/template.yaml


Outputs:
  IAMStackOutput:
    Description: Outputs from IAM stack
    Value: !Ref IAMStack

  CognitoStackOutput:
    Description: Outputs from cognito stack
    Value: !Ref CognitoStack

  DynamoDBStackOutput:
    Description: Outputs from dynamodb stack
    Value: !Ref DynamoDBStack

  AuthFeatureOutput:
    Description: Outputs from Auth AuthFeature
    Value: !Ref AuthFeature