AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Google OAuth and common libraries layer for CAMMI

Resources:
  IntelligentLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: intelligent-layer
      Description: Shared dependencies for Google login, requests, cachecontrol, etc.
      ContentUri: intelligent-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  CrawlerLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: firecrawl-layer
      Description: Shared dependencies for Google login, requests, cachecontrol, etc.
      ContentUri: firecrawl-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  OpenAILibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: openai-layer
      Description: Shared dependencies for Google login, requests, cachecontrol, etc.
      ContentUri: openai-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  DuckLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: duck-layer
      Description: Shared dependencies for Google login, requests, cachecontrol, etc.
      ContentUri: duck-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

  PDFLibrariesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pdf-layer
      Description: Shared dependencies for PDF text extraction using pdfplumber.
      ContentUri: pdf-layer.zip
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete

Outputs:
  IntelligentLibrariesLayerArn:
    Description: ARN of the Google Libraries Layer
    Value: !Ref IntelligentLibrariesLayer
    Export:
      Name: IntelligentLibrariesLayerArn

  CrawlerLibrariesLayerArn:
    Description: ARN of the Google Libraries Layer
    Value: !Ref CrawlerLibrariesLayer
    Export:
      Name: CrawlerLibrariesLayerArn

  OpenAILibrariesLayerArn:
    Description: ARN of the Google Libraries Layer
    Value: !Ref OpenAILibrariesLayer
    Export:
      Name: OpenAILibrariesLayerArn

  DuckLibrariesLayerArn:
    Description: ARN of the Google Libraries Layer
    Value: !Ref DuckLibrariesLayer
    Export:
      Name: DuckLibrariesLayerArn

  PDFLibrariesLayerArn:
    Description: ARN of the PDF Libraries Layer
    Value: !Ref PDFLibrariesLayer
    Export:
      Name: PDFLibrariesLayerArn